[book]
authors = ["Glyn Normington"]
language = "en"
multilingual = false
src = "src"
title = "German Book"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/maverickcasanova/book"
site-url = "https://saketsinha.de/book/"
